version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - oleg-nenashev
  - runzexia
  ignore:
  - dependency-name: io.jenkins.plugins*
    versions:
    - ">= 0"
  - dependency-name: org.jenkins-ci.main:jenkins-core
    versions:
    - ">= 0"
  - dependency-name: org.jenkins-ci.plugins*
    versions:
    - ">= 0"
