
version: 1
update_configs:
- package_manager: "java:maven"
  directory: "/"
  update_schedule: "weekly"
  default_reviewers:
    - "oleg-nenashev"
    - "runzexia"
  ignored_updates:
    - match:
        dependency_name: "org.jenkins-ci.main:jenkins-core"
    - match:
        dependency_name: "org.jenkins-ci.plugins*"
    - match:
        dependency_name: "io.jenkins.plugins*"
  allowed_updates:
    - match:
        dependency_name: "org.jenkins-ci.plugins:plugin-pom"
